sudo: required
language: node_js
node_js:
  - "10"

install:
  - cd client && npm install
  - cd ../server && npm install
script:
  - cd ../client && npm test
  - cd ../server && npm test

cache: npm
