sudo: required
language: node_js
cache: npm

node_js:
  - "10"
services:
  - docker

before_install:
  - echo "$HEROKU_API_KEY" | docker login -u _ --password-stdin registry.heroku.com
install:
  - cd client && npm install
  - cd ../server && npm install
script:
  - cd ../client && npm run lint && npm test -- --coverage
  - cd ../server && npm run lint && npm test -- --coverage
  - cat ../client/coverage/lcov.info >> ./coverage/lcov.info
  - cd .. && cat ./server/coverage/lcov.info | ./server/node_modules/coveralls/bin/coveralls.js
deploy:
  provider: script
  script:
    cd .. && docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME;
  on:
    branch: master
